General Setting: >
  Path to GEM to be investigated

# python main.py -c /Users/baeuerle/Organisation/Masterarbeit/C_striatum_GEMs/code/refineGEMs_config.yaml

model: '../C_striatum_GEMs/models/Cstr_TS.xml'
# Set the out path for all analysis files
out_path: '../C_striatum_GEMs/analysis/growth_sim_comp/'

Settings for scripts that investigate the model: >
  These are only necessary if none of the scripts to manipulate the model are used.

# Set to TRUE if you want pngs that aid in model inevstigation, will be saved to a folder called 'visualization'
visualize: FALSE

# Set the basis medium to simulate growth from
growth_basis: 'default_uptake' # 'default_uptake' or 'minimal_uptake'

# Settings if you want to compare multiple models
multiple: TRUE
multiple_paths: # enter as many paths as you need below
  - '../C_striatum_GEMs/models/Cstr_TS.xml'
  - '../C_striatum_GEMs/models/Cstr_1197.xml'
  - '../C_striatum_GEMs/models/Cstr_1115.xml'
  - '../C_striatum_GEMs/models/Cstr_1116.xml'
  - '../C_striatum_GEMs/models/Cstr_KC-Na-01.xml'
single: FALSE

# media to simulate growth from, just comment the media you do not want with a #
media: 
  #- 'SNM3'
  - 'RPMI'
  - 'LB'
  - 'M9'
  - 'CGXII'
  #- 'CasA'

# determine whether the memote score should be calculated, default: FALSE
memote: FALSE

# compare metabolites to the ModelSEED database
modelseed: FALSE # set to False if not needed


Settings for scripts that manipulate the model: >
  They are all split into the ON / OFF switch (TRUE / FALSE) and additional settings like a path to where the new model should be saved.

model_out: '../rg_out/test.xml' # path and filename to where to save the modified model
entrez_email: 'famke.baeuerle@student.uni-tuebingen.de' # necessary to access NCBI API

### Addition of KEGG Pathways as Groups ###
keggpathways: TRUE

### SBO-Term Annotation ###
sboterms: TRUE

### Model polishing ### The database of the model identifiers needs to be specified with 'id_db'
polish: FALSE
id_db: 'BIGG' # Required! 
# Possible identifiers, currently: BiGG & VMH
# For other IDs the `polish` function in `polish.py` might need adjustment
lab_strain: FALSE # Needs to be set to ensure that protein IDs get the 'bqbiol:isHomologTo' qualifier
                  # & to set the locus_tag to the ones obtained by the annotation
protein_fasta: '' # Path to used CarveMe input file, if exists; Needs to be set for lab_strain: True

### Charge correction ###
charge_corr: TRUE

### Manual Curation ###
man_cur: TRUE
man_cur_type: 'metabs' # either 'gapfill' or 'metabs'
man_cur_table: 'data/manual_curation.xlsx'

### Automatic gap filling ###
# All parameters are required for all db_to_compare choices except:
# - organismid which is only required for db_to_compare: 'KEGG'/'KEGG+BioCyc'
# - and biocyc_files which is not required for 'KEGG'
gap_analysis: FALSE
gap_analysis_params:
  db_to_compare: 'KEGG'  # One of the choices KEGG|BioCyc|GFF|KEGG+BioCyc
  organismid: 'T05059'  # Needs to be specified for KEGG
  gff_file: 'data/cstr.gff'  # Path to RefSeq GFF file 
  biocyc_files: 
    - 'Path0'  # Path to TXT file containing a SmartTable from BioCyc with the columns 'Accession-2' 'Reaction of gene' (-)
    - 'Path1'  # Path to TXT file containing a SmartTable with all reaction relevant information (*)
    - 'Path2'  # Path to TXT file containing a SmartTable with all metabolite relevant information (+)
    - 'Path3'  # Path to protein FASTA file used as input for CarveMe (Needed to get the protein IDs from the locus tags)
# (-) If the organism is not in BioCyc retrieve a table mapping all reactions in BioCyc to the corresponding sequence
# (*) 'Reaction' 'Reactants of reaction' 'Products of reaction' 'EC-Number' 'Reaction-Direction' 'Spontaneous?'
# (+) 'Compound' 'Object ID' 'Chemical Formula' 'InChI-Key' 'ChEBI'
# For all BioCyc files the order should be the same. If the organism does not occur in the BioCyc database the
# complete tables for reactions can be used with the same columns.
gapfill_model: FALSE
gap_analysis_file: 'Path to Excel file with which gaps in model should be filled'
# Either obtained by running gapfill_analysis/Created by hand with the same structure as the result file from gapfill_analysis
# Example Excel file to fill in by hand: data/modelName_gapfill_analysis_date_example.xlsx