name: FROG analysis of all models

on:
  workflow_dispatch
  
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
       persist-credentials: false
       fetch-depth: 0
       
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: python -m pip install fbc-curation
    
    - name: Install dependencies
      run: python -m pip install pandas==1.4.4

    - name: Install dependencies
      run: python -m pip install numpy==1.19.5
        
    - name: Create FROG report
      run: |
        runfrog -i ./models/Cstr_TS.xml -o ./FROG/Cstr_TS_FROG.omex
        runfrog -i ./models/Cstr_1197.xml -o ./FROG/Cstr_1197_FROG.omex
        runfrog -i ./models/Cstr_111197.xml -o ./FROG/Cstr_111197_FROG.omex
        runfrog -i ./models/Cstr_111115.xml -o ./FROG/Cstr_111115_FROG.omex
        runfrog -i ./models/Cstr_KC-Na-01.xml -o ./FROG/Cstr_KC-Na-01_FROG.omex
      
    - name: Unzip Omex files for easier access
      run: |
        unzip ./FROG/Cstr_TS_FROG.omex -d ./FROG/Cstr_TS
        rm ./FROG/Cstr_TS/model.xml
        rm ./FROG/Cstr_TS/manifest.xml
        cp -R ./FROG/Cstr_TS/FROG/cameo ./FROG/Cstr_TS
        rm -R ./FROG/Cstr_TS/FROG/cameo
        cp -R ./FROG/Cstr_TS/FROG/cobrapy ./FROG/Cstr_TS
        rm -R ./FROG/Cstr_TS/FROG/cobrapy
        rm -r ./FROG/Cstr_TS/FROG/
        unzip ./FROG/Cstr_1197_FROG.omex -d ./FROG/Cstr_1197
        rm ./FROG/Cstr_1197/model.xml
        rm ./FROG/Cstr_1197/manifest.xml
        cp -R ./FROG/Cstr_1197/FROG/cameo ./FROG/Cstr_1197
        rm -R ./FROG/Cstr_1197/FROG/cameo
        cp -R ./FROG/Cstr_1197/FROG/cobrapy ./FROG/Cstr_1197
        rm -R ./FROG/Cstr_1197/FROG/cobrapy
        rm -r ./FROG/Cstr_1197/FROG/
        unzip ./FROG/Cstr_1115_FROG.omex -d ./FROG/Cstr_1115
        rm ./FROG/Cstr_1115/model.xml
        rm ./FROG/Cstr_1115/manifest.xml
        cp -R ./FROG/Cstr_1115/FROG/cameo ./FROG/Cstr_1115
        rm -R ./FROG/Cstr_1115/FROG/cameo
        cp -R ./FROG/Cstr_1115/FROG/cobrapy ./FROG/Cstr_1115
        rm -R ./FROG/Cstr_1115/FROG/cobrapy
        rm -r ./FROG/Cstr_1115/FROG/
        unzip ./FROG/Cstr_1116_FROG.omex -d ./FROG/Cstr_1116
        rm ./FROG/Cstr_1116/model.xml
        rm ./FROG/Cstr_1116/manifest.xml
        cp -R ./FROG/Cstr_1116/FROG/cameo ./FROG/Cstr_1116
        rm -R ./FROG/Cstr_1116/FROG/cameo
        cp -R ./FROG/Cstr_1116/FROG/cobrapy ./FROG/Cstr_1116
        rm -R ./FROG/Cstr_1116/FROG/cobrapy
        rm -r ./FROG/Cstr_1116/FROG/
        unzip ./FROG/Cstr_KC-Na-01_FROG.omex -d ./FROG/Cstr_KC-Na-01
        rm ./FROG/Cstr_KC-Na-01/model.xml
        rm ./FROG/Cstr_KC-Na-01/manifest.xml
        cp -R ./FROG/Cstr_KC-Na-01/FROG/cameo ./FROG/Cstr_KC-Na-01
        rm -R ./FROG/Cstr_KC-Na-01/FROG/cameo
        cp -R ./FROG/Cstr_KC-Na-01/FROG/cobrapy ./FROG/Cstr_KC-Na-01
        rm -R ./FROG/Cstr_KC-Na-01/FROG/cobrapy
        rm -r ./FROG/Cstr_KC-Na-01/FROG/

    - name: Commit FROG report
      id: commit
      run: |
        git config --local user.email "famke.baeuerle@gmail.com"
        git config --local user.name "famosab"
        git add --all
        if [-z "$(git status --porcelain)"]; then
           echo "::set-output name=push::false"
        else
           git commit -m "Update FROG Report" -a
           echo "::set-output name=push::true"
        fi
 
    - name: Push changes of the report
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
